---
# SELinux
- name: disable state of SELinux
  selinux: state=disabled

# Apache
- name: install the latest version of Apache
  yum: name=httpd
  notify: restart service httpd

- name: start and enable service httpd
  service: name=httpd state=started enabled=yes

# MariaDB
- name: install the latest version of MariaDB
  yum: name=mariadb-server
  notify: restart service mariadb

- name: start and enable service mariadb
  service: name=mariadb state=started enabled=yes

- name: find out the zabbix database
  command: mysql -u root -e 'SHOW DATABASES;'
  register: databases
  changed_when: false

- name: initialize zabbix database
  script: roles/zabbixserver/files/initialize.sh
  when: databases.stdout.find('zabbix') == -1

# Zabbix
- name: install the latest version of Zabbix server packages
  yum: name={{ item.name }} state=latest
  with_items: zabbix_packages
  notify: restart service zabbix-server

- name: deploy php configuration
  copy: src=php.ini dest=/etc/php.ini
  notify: restart service httpd

- name: deploy zabbix web configuration
  copy: src=zabbix.conf.php dest=/etc/zabbix/web/zabbix.conf.php

- name: create a zabbix server directory
  file: path=/etc/systemd/system/zabbix-server.service.d state=directory

- name: deploy zabbix service environment variables
  template: src=10-environment.conf.j2 dest=/etc/systemd/system/zabbix-server.service.d/10-environment.conf
  notify: restart service zabbix-server

- name: deploy zabbix server configuration
  copy: src=zabbix_server.conf dest=/etc/zabbix_server.conf
  notify: restart service zabbix-server

- name: start and enable service zabbix-server
  service: name=zabbix-server-mysql state=started enabled=no
