---
- name: install the latest version of Apache
  yum: name=httpd
  notify:
  - restart the httpd
- name: start and enable service httpd
  service: name=httpd state=started enabled=yes

- name: install the latest version of MariaDB
  yum: name=mariadb-server
  notify:
  - restart the mariadb
- name: start and enable service mariadb
  service: name=mariadb state=started enabled=yes

- name: install the latest version of Zabbix server packages
  yum: name={{ item.name }} state=latest
  with_items: zabbix_packages
  notify:
  - restart zabbix server
- name: start and enable service zabbix-server
  service: name=zabbix-server-mysql state=started enabled=no

- name: initialize zabbix database
  script: "{{ playbook_dir }}/roles/zabbixserver/files/initialize.sh"
