---
- name: install the latest version of zabbix-agent
  yum: name=zabbix22-agent state=latest
  notify:
  - restart the zabbix-agent
- name: start and enable service zabbix agent
  service: name=zabbix-agent state=started enabled=yes
