---
- name: create a zabbix server directory
  file: path=/etc/systemd/system/zabbix-server.service.d state=directory

- name: deploy zabbix service environment variables
  template: src=10-environment.conf.j2 dest=/etc/systemd/system/zabbix-server.service.d/10-environment.conf
  notify: restart service zabbix-server
