---
- name: restart service httpd
  service: name=httpd state=restarted
- name: restart service mariadb
  service: name=mariadb state=restarted
- name: restart service zabbix-server
  service: name=zabbix-server state=restarted
