---
- name: restart httpd
  service: name=httpd state=restarted
- name: restart mariadb
  service: name=mariadb state=restarted
- name: restart zabbix server
  service: name=zabbix-server state=restarted
